pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}


plugins {
    id("io.github.5hmlA.vcl") version "2026.09.06"
}

vcl {
    doOverride {
        version("gene-cartoon", "2026.10.06")
    }
}

dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "ViewDsl"
include ':app'
include ':view-dsl'
