plugins {
    id 'com.android.application'
    alias(vcl.plugins.gene.android)
    alias(vcl.plugins.gene.compose)
    alias(vcl.plugins.kotlin.android)
}

android {
    namespace 'osp.sparkj.viewdsl'
    buildFeatures {
        viewBinding true
    }
}

dependencies {
    implementation project(':view-dsl')
    implementation libs.androidx.activity.ktx
    implementation libs.androidx.appcompat
    implementation libs.androidx.constraintlayout
    implementation libs.material
    implementation vcl.gene.cartoon
    implementation vcl.androidx.preference.ktx
//    implementation vcl.androidx.activity.ktx
    implementation vcl.androidx.constraintlayout
    implementation vcl.lottie
    implementation vcl.gene.adapter
    implementation vcl.androidx.appcompat
    implementation vcl.google.material
    implementation vcl.androidx.constraintlayout

    // Sticker pipeline - segmentation backends
    implementation libs.segmentation.selfie
    implementation libs.tasks.vision
}